spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET:yP5mL9qB7sT2uH4wF8xG3cV0zA1rE6dM}